### ISSUE TITLE
Tasks are not processed in a closed application

### ISSUE THREAD

**Issue by atomoc** [JoaoLSS/react-native-background-worker#11]
Tell me, please, how to achieve the work of tasks with the application closed, is this generally available?

The WorkManager documentation says that it is available:
![image](https://user-images.githubusercontent.com/465108/84603588-20656780-ae98-11ea-8123-bc513ec4689e.png)

If this is unrealistic, why?

**Comment by JoaoLSS** [comment]
it doesnt work because unlike the java process, the js process in which react runs is destroyed when the app is closed, so the registered headless task is not listening anymore, I'm looking into starting the js process back again, but there is no way to register the headless task.
