### ISSUE TITLE
Ordered queue

### ISSUE THREAD

**Issue by atomoc** [JoaoLSS/react-native-background-worker#12]
Now there is no execution order, that is, if a task is created with the queue type with data:
1
2
3
4

then their call will be done in the reverse order in blocking mode when the device is locked, or even in which it is not clear.

Can this be fixed? Do not execute the second until success in the first is returned?

**Comment by JoaoLSS** [comment]
because workContinuation is not implemented on the native side, so each worker is detached form one another, and the workmanager will call each one with no particular order, maybe in the future I could implement a workContinuation method so there is possible to chain workers

**Comment by atomoc** [comment]
How to get task id in workflow? Everything is in _this_, but only there is no identifier.

**Comment by atomoc** [comment]
I want to use AsyncStorage to solve the problem by writing identifiers to it by type id0, id1, id2, id3, then check which queue the current workflow is if (indexOf (str.split (','), id0)) {deleteIdFromAsyncStorage(id0); return {result: 'retry'};}

**Comment by atomoc** [comment]
Although it is possible to transfer a index number to payload.

**Comment by atomoc** [comment]
Nothing happens, the same task restarts. Apparently all the same there is an order, only it is the reverse, can I somehow turn it over? For example, js uses push to place an element at the end of an array, can you do the same here?

**Comment by atomoc** [comment]
@JoaoLSS 
> because workContinuation is not implemented on the native side, so each worker is detached form one another, and the workmanager will call each one with no particular order, maybe in the future I could implement a workContinuation method so there is possible to chain workers

![image](https://user-images.githubusercontent.com/465108/86518226-9f671380-be38-11ea-9ec7-81495a0b72e4.png)
Can "beginWith" or "then" help solve the problem with the reverse order? I just don’t understand why to put new tasks at the top of the queue.

It turns out that my task cannot be solved in any way without interfering with the native code.

**Comment by atomoc** [comment]
Clear, this is just about WorkContinuation. Is it difficult? Will I be able to do it myself? I have never worked with Java. I will only need to adhere to the https://developer.android.com/reference/androidx/work/WorkContinuation instructions.

**Comment by atomoc** [comment]
I found a solution, quite simple, it is strange that I had not guessed before. It is necessary to use asyncstorage by placing payloads in it as an array, and in workflow, take the first element of the array from asyncstorage and after successful execution remove it from the array and so on until the task ends. So it is possible without WorkContinuation. Thanks!
