### ISSUE TITLE
[Question] Is this project still maintained?

### ISSUE THREAD

**Issue by radaalinmihai** [JoaoLSS/react-native-background-worker#13]
And if so, what should I do if I wanted to execute a task everyday at midnight? What would be the best aproach?

**Comment by atomoc** [comment]
It is supported very very implicitly, the author is apparently very busy and unable to answer any questions in a timely manner.

This package will not allow you to solve your problem, as it does not create a service that works when your application is closed.

**Comment by atomoc** [comment]
Try forks [react-native-background-task](https://github.com/jamesisaac/react-native-background-task), this is the only chance to solve your problem, as it seems to me.

**Comment by JoaoLSS** [comment]
Yeah, I'm currently busy, but I want to update this module soon, I'll get feature requests and try to implement them, PRs are also welcomed

**Comment by JoaoLSS** [comment]
> And if so, what should I do if I wanted to execute a task everyday at midnight? What would be the best aproach?

I think this is a workmanager limitation, I didn't see anything on the docs about scheduling tasks with a precise time, if you find something, please let me know
