### ISSUE TITLE
Jobs not getting persisted

### ISSUE THREAD

**Issue by davevilela** [JoaoLSS/react-native-background-worker#20]
I have noticed that the jobs enqueued are not being persisted upon closing and reopening the App.

**To Reproduce**
1. Try registering long duration jobs such as uploading a bunch of images and persisting it's progress on a realm database.
2. Kill app and reopen it.
3. The worker will no longer start up and continue processing

**Smartphone (please complete the following information):**
 - Device: Galaxy S10
 - OS: Android 10

**Comment by JoaoLSS** [comment]
can you better explain the process that you are taking? did you schedule one single job to upload a bunch of images or one job per image? How are you persisting the progress on realm?

**Comment by davevilela** [comment]
> can you better explain the process that you are taking? did you schedule one single job to upload a bunch of images or one job per image? How are you persisting the progress on realm?

I have a model called "Item" on my database that has a collection of "media", and each media has it's own upload status. The way i persist the progress in realm is either mark the media as sent or pending. Whenever i register the job that takes care of uploading the all the media for each Item, and close the application, the job is not persisted, and i have to query realm to find out what Items are pending and register them again... I think the work manager was supposed to take care of the queue by itself... Correct me if I'm wrong...

**Comment by JoaoLSS** [comment]
Can you replicate this behaviour and send to me? How do you update your database acordingly? Do you fetch each job status on startup using its id?
