### ISSUE TITLE
Reuest on writing more examples

### ISSUE THREAD

**Issue by geocfu** [JoaoLSS/react-native-background-worker#4]
Hello,
would it be possible to include an example app with the examples from the readme?
I am very interested in using this library.
If you can provide me with some extra details i can build it myself and pull request it.
Thank you.

**Comment by geocfu** [comment]
Any news?

Thanks a lot.

**Comment by JoaoLSS** [comment]
I will try to release a new version in the next weeks, got back from vacation only this week.

**Comment by geocfu** [comment]
Any news?

**Comment by JoaoLSS** [comment]
I've finished the periodic example and fixed some bugs, the new code is in the dev branch and the example in the PeriodicExample one, tomorrow I intend to finish the queue example and release the 0.0.5 version on npm =D

**Comment by geocfu** [comment]
Thank you very much. Also as a suggestion, when you finalize the examples, you can place them inside the master branch under the folder "examples". This way, it follows the general pattern i have stumbled upon and has become natural to look for this folder now.

Thank you!

**Comment by JoaoLSS** [comment]
The two examples are on the examples folder, and the 0.0.5 version is published on npm!
